baseURL = "https://www.johndlewis.com/blog/"
languageCode = "en-us"
title = "John D. Lewis - blog"

#theme = "ananke"
theme = "tale"
#theme = "hugo-theme-dream"

# sectionPagesMenu = "main"

[params]
  github="https://www.github.com/balain/"
  linkedin="https://www.linkedin.com/in/johndavidlewis/"
  twitter="https://www.twitter.com/balinjdl/"
  keybase="https://keybase.io/balinjdl"
  author="John D. Lewis"

  js=["/js/fa-all.js"]

  css=[ 
    "/css/fa-all.css",
    "/css/jdl.css" 
  ]

[[Menus.main]]

